on:
  push:
    paths:
      - '*.rs'
      - 'src/**.rs'
  pull_request:
    paths:
      - '*.rs'
      - 'src/**.rs'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for tabs in source code
        run: |
          ! find -name '*.rs' -exec grep -PHn '\t' {} +
